on:
  push:
    branches:
      - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'Iac/*'
      - '.github/workflows/apps30-infra.yml'

on: [push]

name: apps30-infra

jobs:
  build:
    runs-on: self-hosted
    steps:
    
    # checkout branch
    - uses: actions/checkout@master

    # log into Azure
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # create resource group
    - name: 'Create Resource Group'
      run: |
        az group create --subscription "${{ secrets.SUBSCRIPTION_NAME }}" --name ${{ secrets.RESOURCE_GROUP }} --location ${{ secrets.LOCATION }}
    
    # create VNet
    - name: 'Create Virtual Network'
      run: |
        az network vnet create --name igniteapps30vnet --subscription "${{ secrets.SUBSCRIPTION_NAME }}" --resource-group ${{ secrets.RESOURCE_GROUP }} --subnet-name default

    # create cosmos db
    - name: 'Create Cosmos DB'
      run: |
        az cosmosdb create --name ${{ secrets.COSMOS_DB_NAME }}
    
    # create SQL Instance
    - name: 'Create SQL Instance'
      run: |
        az sql server create --location ${{ secrets.LOCATION }} --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.SQL_DB_NAME }} --admin-user ${{ secrets.SQL_ADMIN }} --admin-password ${{ secrets.SQL_PASSWORD }} --subscription "${{ secrets.SUBSCRIPTION_NAME }}"

        az sql server firewall-rule create --resource-group ${{ secrets.RESOURCE_GROUP }} --server ${{ secrets.SQL_DB_NAME }} --name azure --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0 --subscription "${{ secrets.SUBSCRIPTION_NAME }}"

        az sql db create --resource-group ${{ secrets.RESOURCE_GROUP }} --server ${{ secrets.SQL_DB_NAME }} --name tailwind --subscription "${{ secrets.SUBSCRIPTION_NAME }}"
    
    # create ACR
    - name: 'Create Azure Container Registry'
      run: |
        az acr create --resource-group ${{secrets.RESOURCE_GROUP }} --name ${{ secrets.ACR_NAME }} --sku Basic --subscription "${{ secrets.SUBSCRIPTION_NAME }}" --admin-enabled true

    # logout
    - name: 'Azure logout'
      run: |
        az logout
