on: [push]

name: apps30-containerDeploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # checkout branch
    - uses: actions/checkout@master

    # log into Azure
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # docker login
    - name: 'Docker Login'
      uses: greenie-msft/container-actions/docker-login@master
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # build/push docker image
    - name: 'build/push'
      run: |
        docker build Source/Tailwind.Traders.Web/ -t ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.WEBAPP_NAME }}:$GITHUB_SHA
        docker push ${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.WEBAPP_NAME }}:$GITHUB_SHA
    
    - name: 'Create appservice plan'
      run: |
        az appservice plan create -g ${{ secrets.RESOURCE_GROUP }} -n ${{ secrets.WEBAPP_NAME }}   

    # create webapp
    - name: 'webapp create'
      run: |
        az webapp create --name ${{ secrets.WEBAPP_NAME }} --plan ${{ secrets.WEBAPP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} -i ${{secrets.CONTAINER_REGISTRY}}/${{ secrets.WEBAPP_NAME }}:${{ github.sha }}

    # # deploy webapp
    # - name: 'Azure WebApp Container Deploy'
    #   uses: azure/webapps-container-deploy@v1
    #   with:
    #     app-name: '${{ secrets.WEBAPP_NAME }}'
    #     images: ${{secrets.CONTAINER_REGISTRY}}/${{ secrets.WEBAPP_NAME }}:${{ github.sha }}

    # logout
    - name: 'Azure logout'
      run: |
        az logout
